import * as fs from 'fs';
import * as path from 'path';

const dataDir = path.resolve(__dirname, '../Data');

// Only PawnKindDef — characters and animals that genuinely need plurals
const defTypes = [
  'PawnKindDef',
];

// Only .label and .pawnSingular
const labelPatterns = [
  /\.[lL]abel>([^<]+)<\//,
  /\.pawnSingular>([^<]+)<\//,
];

// Skip these
const skipPatterns = [
  /الأيسر|الأيمن|اليسرى|اليمنى/,   // body parts left/right
  /يافع|صغير|جرو|فرخ|عجل|رضيع/,    // age stages (young/baby)
  /جثة/,                              // corpses
  /\(قيد الإنشاء\)/,                 // under construction
  /\(قادم\)|\(مغادر\)/,              // incoming/leaving
  /\{[^}]+\}/,                        // placeholders
];

function shouldSkip(word: string): boolean {
  if (word.split(' ').length > 5) return true;
  for (const pattern of skipPatterns) {
    if (pattern.test(word)) return true;
  }
  return false;
}

function getAllXmlFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const results: string[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...getAllXmlFiles(fullPath));
    } else if (entry.name.endsWith('.xml')) {
      results.push(fullPath);
    }
  }
  return results;
}

function extractWords(arabicDir: string): Set<string> {
  const words = new Set<string>();
  const defInjectedDir = path.join(arabicDir, 'DefInjected');
  if (!fs.existsSync(defInjectedDir)) return words;

  for (const defType of defTypes) {
    const defTypeDir = path.join(defInjectedDir, defType);
    const files = getAllXmlFiles(defTypeDir);

    for (const file of files) {
      const content = fs.readFileSync(file, 'utf-8');
      const lines = content.split('\n');
      for (const line of lines) {
        for (const pattern of labelPatterns) {
          const match = line.match(pattern);
          if (match) {
            const word = match[1].trim();
            // Skip non-Arabic words entirely
            const hasArabic = /[\u0600-\u06FF]/.test(word);
            if (word && hasArabic && !shouldSkip(word)) {
              words.add(word);
            }
          }
        }
      }
    }
  }

  return words;
}

function updatePluralFile(arabicDir: string, words: Set<string>) {
  const outputPath = path.join(arabicDir, 'WordInfo', 'plural.txt');
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  const existing = new Map<string, string>();
  if (fs.existsSync(outputPath)) {
    const lines = fs.readFileSync(outputPath, 'utf-8').split('\n');
    for (const line of lines) {
      if (line.startsWith('//') || !line.trim()) continue;
      const parts = line.split(';');
      if (parts[0]) existing.set(parts[0].trim(), line.trim());
    }
  }

  const comments = [
    '// Auto-generated by updatePlural.ts',
    '// Add Arabic plural after the semicolon for each word',
    '// Example: مستعمر;مستعمرون',
    '// ---',
  ];

  const outputLines = [...comments];
  const sortedWords = [...words].sort();

  for (const word of sortedWords) {
    if (existing.has(word)) {
      outputLines.push(existing.get(word)!);
    } else {
      outputLines.push(`${word};`);
    }
  }

  fs.writeFileSync(outputPath, outputLines.join('\n'), 'utf-8');
  console.log(`  Updated: ${outputPath}`);
  console.log(`  Total words: ${words.size}`);
  console.log(`  New words: ${[...words].filter(w => !existing.has(w)).length}`);
  console.log(`  Already classified: ${[...words].filter(w => existing.has(w)).length}`);
}

// Get all DLC folders
const dlcFolders = fs.readdirSync(dataDir, { withFileTypes: true })
  .filter(e => e.isDirectory())
  .map(e => path.join(dataDir, e.name));

for (const dlcFolder of dlcFolders) {
  const arabicDir = path.join(dlcFolder, 'Languages', 'Arabic');
  if (!fs.existsSync(arabicDir)) continue;

  console.log(`\nProcessing: ${path.basename(dlcFolder)}`);
  const words = extractWords(arabicDir);
  if (words.size === 0) {
    console.log('  No words found, skipping.');
    continue;
  }
  updatePluralFile(arabicDir, words);
}

console.log('\n✅ Done!');
